server:
  port: 8000
  servlet:
    context-path: /foodOrder
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
   view:
    prefix: /WEB-INF/views/
    suffix: .jsp
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/foodoreder
    username: "goni"   
    password: "010101"
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create # 최초 create 후 나중엔 update로 바꿔야함
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false  # JPA 기본 넘버링 전략
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false